# SPDX-License-Identifier: MIT
# Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
"""Pytest reproducer for the asm v3 BR group bwd kernel regression.

Background
----------
``aiter.flash_attn_varlen_func(..., causal=True, ...)`` uses the
"bottom-right" causal mask (per the docstring at ``aiter/ops/mha.py:2632``).
For ``hdim_q == 128``, ``bf16``, group/varlen mode, and ``seqlen_q >= 17``
the bwd dispatch picks the asm-v3 ``psskddv_group`` kernel
``hsa/gfx950/fmha_v3_bwd/bwd_hd128_bf16_causal_br_a32_psskddv_group.co`` on
gfx950.

That .co was regenerated by upstream AITER PR #2189
("[FIX] address overflow fix on fmha_bwd of gfx942/gfx950", commit
``a375fd97c``, 2026-03-06). The new blob is buggy on gfx950 for large
seqlens (>= ~2048):

These tests pin the regression as standalone, runnable pytest cases so an
AITER-side fix can be validated without involving TransformerEngine. To
prove the kernel itself is the culprit (and not arg plumbing), the same
shapes can be exercised at the C level via
``op_tests/cpp/mha/bwd.exe -prec=bf16 -b=2 -h=24 -h_k=1 -d=128 -s=2048
-s_k=2048 -iperm=1 -operm=1 -mask=b -mode=1 -bwd_v3=1 -v3_atomic_fp32=1``

Usage
-----
::

    pytest -xvs op_tests/test_mha_varlen_bwd_br_regression.py
"""

from __future__ import annotations

import pytest
import torch

import aiter
from aiter.test_mha_common import attention_ref


def _build_varlen_inputs(batch: int, sq: int, sk: int, h: int, hg: int, d: int,
                         dtype: torch.dtype, device: str = "cuda"):
    """Build tightly-packed varlen tensors with uniform per-batch seqlens.

    Returns (q, k, v, cu_seqlens_q, cu_seqlens_k, dout) all in the shapes
    that ``flash_attn_varlen_func`` and ``attention_ref`` consume.
    """
    total_q = batch * sq
    total_k = batch * sk

    # Use ~unit-magnitude inputs (same scale TE/torch test fixtures use). The
    # asm-v3 BR bug's output error scales with input magnitude; tiny inputs
    # mask the catastrophic failure as a small numerical wobble.
    q = torch.empty(total_q, h,  d, dtype=dtype, device=device).normal_(mean=0.0, std=0.5).requires_grad_(True)
    k = torch.empty(total_k, hg, d, dtype=dtype, device=device).normal_(mean=0.0, std=0.5).requires_grad_(True)
    v = torch.empty(total_k, hg, d, dtype=dtype, device=device).normal_(mean=0.0, std=0.5).requires_grad_(True)

    cu_seqlens_q = torch.arange(0, total_q + 1, sq, dtype=torch.int32, device=device)
    cu_seqlens_k = torch.arange(0, total_k + 1, sk, dtype=torch.int32, device=device)

    dout = torch.randn_like(q)
    return q, k, v, cu_seqlens_q, cu_seqlens_k, dout


def _reference_grads(q_flat, k_flat, v_flat, dout_flat,
                     batch: int, sq: int, sk: int, h: int, hg: int, d: int,
                     dtype: torch.dtype):
    """Run ``attention_ref`` on a (b, s, h, d) reshape and pull dQ/dK/dV.

    Uses leaf clones (independent autograd graph from the AITER call) so
    we can compare the two backward results cleanly.
    """
    q_b = q_flat.detach().reshape(batch, sq, h,  d).clone().requires_grad_(True)
    k_b = k_flat.detach().reshape(batch, sk, hg, d).clone().requires_grad_(True)
    v_b = v_flat.detach().reshape(batch, sk, hg, d).clone().requires_grad_(True)
    out_ref, _, _ = attention_ref(q_b, k_b, v_b, causal=True)
    dout_b = dout_flat.detach().reshape(batch, sq, h, d).to(out_ref.dtype)
    out_ref.backward(dout_b)
    # Re-flatten to (total, h, d) to match flash_attn_varlen_func's output layout.
    return (q_b.grad.to(dtype).reshape(batch * sq, h,  d),
            k_b.grad.to(dtype).reshape(batch * sk, hg, d),
            v_b.grad.to(dtype).reshape(batch * sk, hg, d))


def _run_one(batch: int, sq: int, sk: int, h: int, hg: int, d: int,
             dtype: torch.dtype):
    q, k, v, cu_q, cu_k, dout = _build_varlen_inputs(batch, sq, sk, h, hg, d, dtype)

    out, *_ = aiter.flash_attn_varlen_func(
        q, k, v, cu_q, cu_k,
        max_seqlen_q=sq, max_seqlen_k=sk,
        dropout_p=0.0,
        causal=True,                       # bottom-right per docstring (line 2632)
        return_lse=True,
    )

    dq, dk, dv = torch.autograd.grad(out, (q, k, v), grad_outputs=dout)
    dq_ref, dk_ref, dv_ref = _reference_grads(q, k, v, dout, batch, sq, sk, h, hg, d, dtype)

    failures = []
    for name, a, b in (("dQ", dq, dq_ref), ("dK", dk, dk_ref), ("dV", dv, dv_ref)):
        diff = (a.float() - b.float()).abs()
        max_err = diff.max().item()
        # AITER's own bench uses atol=1e-2 (benchmark_mha_bwd.cpp:172).
        atol = 1.6e-2
        frac_wrong = (diff > atol).float().mean().item() * 100.0
        print(f"  {name}: max_abs_err={max_err:.6f}  frac_wrong(>{atol})={frac_wrong:.2f}%")
        if max_err > atol:
            failures.append(f"{name}: max_abs_err {max_err:.6f} > {atol}")

    if failures:
        pytest.fail("\n  ".join(["AITER varlen bwd diverges from reference:"] + failures))


# ---------------------------------------------------------------------------
# Failing shapes — observed dV error 0.03–0.125 in pytest. Pure-MHA shapes
# stay just under tolerance here but are flagged ``valid:n`` by AITER's own
# C-level bench. High-GQA shapes additionally trigger GPU memory-access
# faults in the bench (alignment-dependent — pytest's tensor allocator
# happens to land on safe addresses, hiding the crash but not the error).
# ---------------------------------------------------------------------------

# (label, batch, sq, sk, h, hg, d) — bf16 hdim=128 to land on the broken kernel
_FAILING_SHAPES = [
    # TE cluster 1 (mask_5_1): SBHD post-unpad, sq==sk, GQA 24:1
    ("te_cluster1_b2_h24x1_sq2048",   2, 2048, 2048, 24, 1, 128),
    # TE swa_6_2: GQA 24:4
    ("te_swa6_2_b2_h24x4_sq2048",     2, 2048, 2048, 24, 4, 128),
    # GQA-bisect shapes at sq=sk=2048 — show the wrong-result→crash gradient
    ("bisect_gqa3_1_b2_h3x1_sq2048",  2, 2048, 2048, 3,  1, 128),
    ("bisect_gqa8_1_b2_h8x1_sq2048",  2, 2048, 2048, 8,  1, 128),
    # High-GQA at small seqlen — also fails (GQA matters more than seqlen here)
    ("gqa24x1_small_b2_h24x1_sq200",  2,  200,  200, 24, 1, 128),
]


@pytest.mark.parametrize("label,batch,sq,sk,h,hg,d", _FAILING_SHAPES,
                         ids=[c[0] for c in _FAILING_SHAPES])
def test_br_bwd_regression_fails(label, batch, sq, sk, h, hg, d):
    """The asm-v3 BR psskddv_group kernel is broken on these shapes.

    Observed pytest dV err: 0.03–0.125 (well above bf16 atol=1.6e-2).
    The same shapes invoked at the C level (``op_tests/cpp/mha/bwd.exe``)
    show the more dramatic surface symptoms: ``valid:n`` for low-GQA and
    GPU memory-access faults for GQA ratios ≥ 8:1.
    """
    _run_one(batch, sq, sk, h, hg, d, torch.bfloat16)


# ---------------------------------------------------------------------------
# Passing shapes — pure-MHA, small batch — same kernel, but stays correct
# ---------------------------------------------------------------------------

_PASSING_SHAPES = [
    ("mha_b2_h3x3_sq129",  2, 129, 200, 3, 3, 128),  # AITER's own smoke shape
]


@pytest.mark.parametrize("label,batch,sq,sk,h,hg,d", _PASSING_SHAPES,
                         ids=[c[0] for c in _PASSING_SHAPES])
def test_br_bwd_passes_on_baseline(label, batch, sq, sk, h, hg, d):
    """Same kernel on pure-MHA small-seqlen shapes — expected to pass.

    Confirms the failure is shape-dependent, not a build/load/dispatch
    issue. These shapes match AITER's own ``smoke_test_bwd_v3.sh``.
    """
    _run_one(batch, sq, sk, h, hg, d, torch.bfloat16)
