name: Aiter Benchmark

on:
  pull_request: # for testing
    # types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  aiter_benchmark:
    name: Aiter Benchmark
    uses: ROCm/ATOM/.github/workflows/atom-benchmark.yaml@atom_benchmark_expose
    with:
      deepseek-r1-0528: true
      extra_args: "--kv_cache_dtype fp8 -tp 8"
      param_list: "1024,1024,128,0.8"